language: go
go:
        - "1.8"
        - "1.10.x"
        - master

install:
        - go get github.com/spf13/pflag
        - go get github.com/kenshaw/cznic-ql/common/file
 
script:
        - go test  -v ./...
